COMMON_C = common.c
COMMON = ${COMMON_C} common.h

all: day1 day2 day3p1 day3p2

day1: ${.TARGET}.c ${COMMON}
	${LINK.c} -o ${.TARGET} ${.TARGET}.c ${COMMON_C}

day2: ${.TARGET}.c ${COMMON}
	${LINK.c} -o ${.TARGET} ${.TARGET}.c ${COMMON_C}

day3p1: ${.TARGET}.c ${COMMON}
	${LINK.c} -o ${.TARGET} ${.TARGET}.c ${COMMON_C}

day3p2: ${.TARGET}.c ${COMMON}
	${LINK.c} -o ${.TARGET} ${.TARGET}.c ${COMMON_C}
